import requests
import json
from datetime import date


today = date.today()
date_today = today.strftime("%d/%m/%Y")


#url = "https://stocknewsapi.com/api/v1/category?section=general&items=4&page=1&items=4&token=zz8e1ooyn2o1lmdtdrqyaenm6nl5p3jhfodxhiog"

#data = requests.get(url).json()

data = {'data': [
    {'news_url': 'https://www.marketwatch.com/story/once-the-market-tests-its-june-2022-low-stocks-will-be-poised-to-move-higher-were-not-there-yet-11663802134', 'image_url': 'https://cdn.snapi.dev/images/v1/p/j/im-622820size1777777777777778width800-1553707.jpg', 'title': "Once the market tests its June 2022 low, stocks will be poised to move higher. We're not there yet.", 'text': "There's still too much bullishness on Wall Street, even after the Dow Jones Industrial Average's DJIA, -1.70% 500+ point drop Wednesday following the Federal Reserve's latest meeting and rate hike.", 'source_name': 'Market Watch', 'date': 'Wed, 21 Sep 2022 19:15:00 -0400', 'topics': ['paylimitwall'], 'sentiment': 'Negative', 'type': 'Article'}, 
    {'news_url': 'https://www.marketwatch.com/story/the-dow-tumbled-500-points-because-jerome-powells-fed-isnt-going-to-blink-11663802155', 'image_url': 'https://cdn.snapi.dev/images/v1/y/j/im-628471size1777777777777778width800-1553706.jpg', 'title': "The Dow tumbled 500 points because Jerome Powell's Fed ‘isn't going to blink'", 'text': "It took stock-market investors a while to make up their minds, but when the closing bell sounded on Wednesday it was clear they didn't like what they had heard from the Federal Reserve and its chairman Jerome Powell.", 'source_name': 'Market Watch', 'date': 'Wed, 21 Sep 2022 19:15:00 -0400', 'topics': ['paylimitwall'], 'sentiment': 'Negative', 'type': 'Article'}, 
    {'news_url': 'https://www.marketwatch.com/story/s-p-500-sees-its-third-leg-down-of-more-than-10-heres-what-history-shows-about-past-bear-markets-hitting-new-lows-from-there-according-to-bespoke-11663800352', 'image_url': 'https://cdn.snapi.dev/images/v1/f/k/im-414289size1777777777777778width800-1553688.jpg', 'title': "S&P 500 sees its third leg down of more than 10%. Here's what history shows about past bear markets hitting new lows from there, according to Bespoke.", 'text': 'Stocks fell sharply after the Federal Reserve announced Wednesday that it was raising its benchmark rate by three-quarters of a percentage point as it battles inflation, with the S&P 500 continuing a slide described by Bespoke Investment Group as its third leg down.', 'source_name': 'Market Watch', 'date': 'Wed, 21 Sep 2022 18:45:00 -0400', 'topics': ['paylimitwall'], 'sentiment': 'Negative', 'type': 'Article'},
    {'news_url': 'https://www.youtube.com/watch?v=MNqn_yXbgOY', 'image_url': 'https://cdn.snapi.dev/images/v1/q/q/jim-cramer-breaks-down-the-two-broad-camps-emerging-as-the-fed-battles-inflation-1553710.jpg', 'title': 'Jim Cramer breaks down the two broad camps emerging as the Fed battles inflation', 'text': "CNBC's Jim Cramer on Wednesday explained the two camps of investors that are emerging as the Fed continues its aggressive campaign against inflation.", 'source_name': 'CNBC Television', 'date': 'Wed, 21 Sep 2022 19:25:40 -0400', 'topics': ['cramer', 'madmoney'], 'sentiment': 'Neutral', 'type': 'Video'}, 
    {'news_url': 'https://www.marketwatch.com/story/once-the-market-tests-its-june-2022-low-stocks-will-be-poised-to-move-higher-were-not-there-yet-11663802134', 'image_url': 'https://cdn.snapi.dev/images/v1/p/j/im-622820size1777777777777778width800-1553707.jpg', 'title': "Once the market tests its June 2022 low, stocks will be poised to move higher. We're not there yet.", 'text': "There's still too much bullishness on Wall Street, even after the Dow Jones Industrial Average's DJIA, -1.70% 500+ point drop Wednesday following the Federal Reserve's latest meeting and rate hike.", 'source_name': 'Market Watch', 'date': 'Wed, 21 Sep 2022 19:15:00 -0400', 'topics': ['paylimitwall'], 'sentiment': 'Negative', 'type': 'Article'}, 
    {'news_url': 'https://www.marketwatch.com/story/the-dow-tumbled-500-points-because-jerome-powells-fed-isnt-going-to-blink-11663802155', 'image_url': 'https://cdn.snapi.dev/images/v1/y/j/im-628471size1777777777777778width800-1553706.jpg', 'title': "The Dow tumbled 500 points because Jerome Powell's Fed ‘isn't going to blink'", 'text': "It took stock-market investors a while to make up their minds, but when the closing bell sounded on Wednesday it was clear they didn't like what they had heard from the Federal Reserve and its chairman Jerome Powell.", 'source_name': 'Market Watch', 'date': 'Wed, 21 Sep 2022 19:15:00 -0400', 'topics': ['paylimitwall'], 'sentiment': 'Negative', 'type': 'Article'}, 
    {'news_url': 'https://www.marketwatch.com/story/s-p-500-sees-its-third-leg-down-of-more-than-10-heres-what-history-shows-about-past-bear-markets-hitting-new-lows-from-there-according-to-bespoke-11663800352', 'image_url': 'https://cdn.snapi.dev/images/v1/f/k/im-414289size1777777777777778width800-1553688.jpg', 'title': "S&P 500 sees its third leg down of more than 10%. Here's what history shows about past bear markets hitting new lows from there, according to Bespoke.", 'text': 'Stocks fell sharply after the Federal Reserve announced Wednesday that it was raising its benchmark rate by three-quarters of a percentage point as it battles inflation, with the S&P 500 continuing a slide described by Bespoke Investment Group as its third leg down.', 'source_name': 'Market Watch', 'date': 'Wed, 21 Sep 2022 18:45:00 -0400', 'topics': ['paylimitwall'], 'sentiment': 'Negative', 'type': 'Article'},
    {'news_url': 'https://www.youtube.com/watch?v=MNqn_yXbgOY', 'image_url': 'https://cdn.snapi.dev/images/v1/q/q/jim-cramer-breaks-down-the-two-broad-camps-emerging-as-the-fed-battles-inflation-1553710.jpg', 'title': 'Jim Cramer breaks down the two broad camps emerging as the Fed battles inflation', 'text': "CNBC's Jim Cramer on Wednesday explained the two camps of investors that are emerging as the Fed continues its aggressive campaign against inflation.", 'source_name': 'CNBC Television', 'date': 'Wed, 21 Sep 2022 19:25:40 -0400', 'topics': ['cramer', 'madmoney'], 'sentiment': 'Neutral', 'type': 'Video'}, 
    {'news_url': 'https://www.marketwatch.com/story/once-the-market-tests-its-june-2022-low-stocks-will-be-poised-to-move-higher-were-not-there-yet-11663802134', 'image_url': 'https://cdn.snapi.dev/images/v1/p/j/im-622820size1777777777777778width800-1553707.jpg', 'title': "Once the market tests its June 2022 low, stocks will be poised to move higher. We're not there yet.", 'text': "There's still too much bullishness on Wall Street, even after the Dow Jones Industrial Average's DJIA, -1.70% 500+ point drop Wednesday following the Federal Reserve's latest meeting and rate hike.", 'source_name': 'Market Watch', 'date': 'Wed, 21 Sep 2022 19:15:00 -0400', 'topics': ['paylimitwall'], 'sentiment': 'Negative', 'type': 'Article'}, 
    {'news_url': 'https://www.marketwatch.com/story/the-dow-tumbled-500-points-because-jerome-powells-fed-isnt-going-to-blink-11663802155', 'image_url': 'https://cdn.snapi.dev/images/v1/y/j/im-628471size1777777777777778width800-1553706.jpg', 'title': "The Dow tumbled 500 points because Jerome Powell's Fed ‘isn't going to blink'", 'text': "It took stock-market investors a while to make up their minds, but when the closing bell sounded on Wednesday it was clear they didn't like what they had heard from the Federal Reserve and its chairman Jerome Powell.", 'source_name': 'Market Watch', 'date': 'Wed, 21 Sep 2022 19:15:00 -0400', 'topics': ['paylimitwall'], 'sentiment': 'Negative', 'type': 'Article'}, 
    {'news_url': 'https://www.marketwatch.com/story/s-p-500-sees-its-third-leg-down-of-more-than-10-heres-what-history-shows-about-past-bear-markets-hitting-new-lows-from-there-according-to-bespoke-11663800352', 'image_url': 'https://cdn.snapi.dev/images/v1/f/k/im-414289size1777777777777778width800-1553688.jpg', 'title': "S&P 500 sees its third leg down of more than 10%. Here's what history shows about past bear markets hitting new lows from there, according to Bespoke.", 'text': 'Stocks fell sharply after the Federal Reserve announced Wednesday that it was raising its benchmark rate by three-quarters of a percentage point as it battles inflation, with the S&P 500 continuing a slide described by Bespoke Investment Group as its third leg down.', 'source_name': 'Market Watch', 'date': 'Wed, 21 Sep 2022 18:45:00 -0400', 'topics': ['paylimitwall'], 'sentiment': 'Negative', 'type': 'Article'},
    {'news_url': 'https://www.youtube.com/watch?v=MNqn_yXbgOY', 'image_url': 'https://cdn.snapi.dev/images/v1/q/q/jim-cramer-breaks-down-the-two-broad-camps-emerging-as-the-fed-battles-inflation-1553710.jpg', 'title': 'Jim Cramer breaks down the two broad camps emerging as the Fed battles inflation', 'text': "CNBC's Jim Cramer on Wednesday explained the two camps of investors that are emerging as the Fed continues its aggressive campaign against inflation.", 'source_name': 'CNBC Television', 'date': 'Wed, 21 Sep 2022 19:25:40 -0400', 'topics': ['cramer', 'madmoney'], 'sentiment': 'Neutral', 'type': 'Video'}, 
    {'news_url': 'https://www.marketwatch.com/story/once-the-market-tests-its-june-2022-low-stocks-will-be-poised-to-move-higher-were-not-there-yet-11663802134', 'image_url': 'https://cdn.snapi.dev/images/v1/p/j/im-622820size1777777777777778width800-1553707.jpg', 'title': "Once the market tests its June 2022 low, stocks will be poised to move higher. We're not there yet.", 'text': "There's still too much bullishness on Wall Street, even after the Dow Jones Industrial Average's DJIA, -1.70% 500+ point drop Wednesday following the Federal Reserve's latest meeting and rate hike.", 'source_name': 'Market Watch', 'date': 'Wed, 21 Sep 2022 19:15:00 -0400', 'topics': ['paylimitwall'], 'sentiment': 'Negative', 'type': 'Article'}, 
    {'news_url': 'https://www.marketwatch.com/story/the-dow-tumbled-500-points-because-jerome-powells-fed-isnt-going-to-blink-11663802155', 'image_url': 'https://cdn.snapi.dev/images/v1/y/j/im-628471size1777777777777778width800-1553706.jpg', 'title': "The Dow tumbled 500 points because Jerome Powell's Fed ‘isn't going to blink'", 'text': "It took stock-market investors a while to make up their minds, but when the closing bell sounded on Wednesday it was clear they didn't like what they had heard from the Federal Reserve and its chairman Jerome Powell.", 'source_name': 'Market Watch', 'date': 'Wed, 21 Sep 2022 19:15:00 -0400', 'topics': ['paylimitwall'], 'sentiment': 'Negative', 'type': 'Article'}, 
    {'news_url': 'https://www.marketwatch.com/story/s-p-500-sees-its-third-leg-down-of-more-than-10-heres-what-history-shows-about-past-bear-markets-hitting-new-lows-from-there-according-to-bespoke-11663800352', 'image_url': 'https://cdn.snapi.dev/images/v1/f/k/im-414289size1777777777777778width800-1553688.jpg', 'title': "S&P 500 sees its third leg down of more than 10%. Here's what history shows about past bear markets hitting new lows from there, according to Bespoke.", 'text': 'Stocks fell sharply after the Federal Reserve announced Wednesday that it was raising its benchmark rate by three-quarters of a percentage point as it battles inflation, with the S&P 500 continuing a slide described by Bespoke Investment Group as its third leg down.', 'source_name': 'Market Watch', 'date': 'Wed, 21 Sep 2022 18:45:00 -0400', 'topics': ['paylimitwall'], 'sentiment': 'Negative', 'type': 'Article'}
    ],'total_pages': 2500}

news = data["data"]

articles = {}

num = 0
for i in news:
    num +=1
    articles["Article"+str(num)] = [i["news_url"], i["image_url"], i["title"], i["text"], i["source_name"], i["date"]]
